# Generated by Django 5.2.9 on 2025-12-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area_sq_km',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='currency_symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='emojiU',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='gdp',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='native',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='numeric_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='phonecode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='postal_code_format',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='postal_code_regex',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='region_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='subregion_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='timezones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='tld',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='wikiDataId',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
