# Generated by Django 5.2.9 on 2025-12-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_area_sq_km_country_capital_country_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='institution_name',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
